---
- hosts: localhost #elocalhost
  connection: local
  vars: 
    ssh_known_hosts:  "{{ groups['dbserver'] }}"
  tasks:
          - name: destroying lxc containers
            lxd_container:
                    name: "{{ item }}" 
                    state: absent
            with_items: "{{ ssh_known_hosts }}" 

- import_playbook: create-lxd.yml

- import_playbook: add-ssh-key.yml

- import_playbook: create-cluster.yml

- import_playbook: create-standby-async.yml
  tags: standby