---
- hosts: all
  gather_facts: false
  tasks:
  # - name: sleep async 
  #   command: sleep 30
  #   async: 20
  #   poll: 5 # worked

  - name: sleep async 
    shell: sleep 30
    async: 20
    poll: 0
    register: sleep_command

  - name: check status
    async_status:
      jid: "{{ sleep_command.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 7
    delay: 5