- name:
  block:
    - name: checking if postgres is available
      become_user: postgres 
      postgresql_info:
              db: postgres
              filter:
              - "!settings" 
      register: pg_ping
  rescue:
    - name: Installing psycopg2 since it does not exists
      apt:
        name: 
          - python3-psycopg2
        state: present

    - name: checking if postgres is available
      become_user: postgres 
      postgresql_info:
              db: postgres
              filter:
              - "!settings" 
      register: pg_ping


- name: postgres_info | is postgres in recovery
  become_user: postgres 
  command: psql -Aqt -c "select pg_is_in_recovery()"
  register: recovery

- name: postgres_info| setting postgres facts
  set_fact:
    Isrecovery: "{{ recovery.stdout }}"
    postgres_version: "{{ pg_ping.version.major }}"
  

    
  
  
