- name:
  block:
    - name: checking if postgres is available
      become_user: postgres 
      postgresql_info:
              db: postgres
              filter:
               - in_recovery 
               - version
               - settings 
      register: pg_ping
  rescue:
    - name: Installing psycopg2 since it does not exists
      apt:
        name: 
          - python3-psycopg2
        state: present

   - name: checking if postgres is available
      become_user: postgres 
      postgresql_info:
              db: postgres
              filter:
               - in_recovery 
               - version
      register: pg_ping
