---
- name: create containers
  # get all host names from inventory
  loop: "{{ group_hosts }}"
  #  loop: "{{ groups['mysql_servers'] }}"
  # use lxd_container module from ansible to create containers
  lxd_container:
    # container name is the hostname
    name: "{{ item }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      alias: "{{ hostvars[item].os_alias  | default('ubuntu/bionic/amd64') }}" #ubuntu/bionic/amd64
    devices:
      # configure network interface
      eth0:
        type: nic
        nictype: bridged
        parent: lxdbr0
        # get ip address from inventory
        ipv4.address: "{{ hostvars[item].ip_address }}"
    # # uncomment if you installed lxd using snap
    # url: unix:/var/snap/lxd/common/lxd/unix.socket
  register: creation

- include: init_install.yml
  loop: "{{ groups['create_3clust'] }}"
  when: creation.changed

