---
- include_role:
    name: schemcodes-postgres_info ## this will get all the basic info, like recovry mode.
    apply:
      become: yes
      check_mode: no

- name: creating user in primary
  become: true
  become_user: postgres
  postgresql_user:
    name: user_dba
    password: test
    role_attr_flags: CREATEDB,NOSUPERUSER
  when: Isrecovery == 'f'