---
- hosts: appserver
  gather_facts: yes
  become: yes
  tasks:
  - name: setup-debian | Installing packages
    apt: 
      name: 
        - gpg 
        - ufw
        - rsync
        - acl
      state: present  
      update_cache: true
    when: ansible_distribution_version.split('.')[0] is version('18','>=')
  
  - name: setup-debian | adding apt postgres key 
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
      state: present
  
  - name: setup-debian | Adding postgres repo
    become: true
    apt_repository:
      repo: 'deb http://apt.postgresql.org/pub/repos/apt/ "{{ ansible_distribution_release }}"-pgdg main'
      filename: postgresql
      state: present
  
  - name: setup-debian | installing postgres
    apt:
      name: 
        - postgresql-{{ postgres_version }}
        - postgresql-server-dev-{{ postgres_version }}
      state: present

  - name: create folder in root
    file:
      path: /var/lib/postgresql/appsettings
      state: directory
      group: postgres
      owner: postgres
  
  - name: touch file
    file:
      path: /var/lib/postgresql/appsettings/app.conf
      state: touch

  - name: 
    lineinfile:
      path: /var/lib/postgresql/appsettings/app.conf
      line: "ssh {{ item }}"
      state: present
    with_items:
      - "{{ groups['dbserver'] }}"
      

  # - name: copy dbhosts to conf file
  #   copy:
  #    content: "{{ groups['dbserver'] }}"
  #    dest: /var/lib/postgresql/appsettings/app.conf
  #    group: postgres
  #    owner: postgres
    
    
  # - name: initializing the db
  #   copy:
  #     content: 
  #   with_items:
  #     "{{ groups['dbserver'] }}"
  #   command: "pgbench -h {{ item }} -i"
  #   with_items:  "{{ groups['dbserver'] }}"


    
  