---
- include_role:
    name: schemcodes-postgres-basic-info
    apply:
      become: yes

- name: creating index with a timeout of 1000 sec and will poll every 10s
  become_user: postgres
  postgresql_idx:
    db: postgres
    table: pgbench_accounts
    columns: bid
    name: idx_bid_pgbench_accounts
  async: 1000
  poll: 10
  when: Isrecovery == 'f' and async_enabled 


- name: creating index with a timeout of 1000 sec and will poll every 10s
  become_user: postgres
  postgresql_idx:
    db: postgres
    table: pgbench_accounts
    columns: bid
    name: idx_bid_pgbench_accounts
  when: Isrecovery == 'f' and not async_enabled 