---
# Variable configuration.
- include_tasks: variables.yml

- include_tasks: set_facts.yml

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
  when: not pgdata_dir_version.stat.exists

- include_tasks: configure.yml
  tags:
  - recovery_file

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"


- import_tasks: set_users.yml
  tags: user


- name: removing the "{{ postgresql_python_library }}"
  apt:
    name: "{{ postgresql_python_library }}"
    state: absent


# - import_tasks: create_standby_folder.yml
#   tags: standby

  #- import_tasks: databases.yml

## create the slave! Not forced
# - import_tasks: slave.yml
#   when: is_slave
  #  tags: [ 'never', 'slave' ]
