---
- name: set fact | Check if PostgreSQL database is in recovery.
  become: true 
  stat:
    path: "{{ postgresql_data_dir }}/recovery.conf"
  register: pgrecovery_check

- set_fact:
    postgresql_binary: "postgresql-{{ postgres_version }}"

- name: Check if PostgreSQL database is initialized.
  become: true
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  
