---
- name: check for master_file
  become: true
  stat:
    path: "/root/master_host.txt"
  register: master_file

 
- name: check for slave_file 
  become: true 
  stat:
    path: "/root/slave_host.txt"
  register: slave_file


